### ISSUE TITLE
Why there is not any fonts to use? (eot, woff, ttf,...)

### ISSUE THREAD

**Issue by ykh** [rastikerdar/vazir-font#17]
Hi :)
So tnx for this nice job.
But I have a problem to use these fonts because of lack of them inside the repository! XD
I had used bower to get it.

**Comment by aziz** [comment]
You can find them [on the release page](https://github.com/rastikerdar/vazir-font/releases)
@rastikerdar It might be helpful to link to releases page in README

**Comment by ykh** [comment]
tnx for reply.
but how can I get release files with bower? we used bower in our project and we don't decide to load vendors by another way :)

**Comment by aziz** [comment]
This repo is not published to bower or npm repositories yet. there was a discussion about it in the issues a while back but I guess @rastikerdar is not yet ready to publish them. 
Anyway event if he wants to do it in the future, it should be done using another repo since the master branch of this repo does not have the built fonts and only includes the source. 

In the meantime you can publish one for your own use but please don't publicize it.

<RANT>
BTW, bower is a dead horse, don't invest on it. Almost everyone agreed that front-end package manager of the future would be npm!
</RANT>

**Comment by rastikerdar** [comment]
سلام
@ykh سپاسگزارم برای گزارش این مورد.
@aziz کاملا حق با شماست و باید لینکی هم به صفحه دانلود ها ایجاد گردد

هر گونه تغییری که به نظرتان مفید آمد در مخزن اعمال کنید مایه امتنان این حقیر خواهد بود.

در مورد برنامه هایی که فرمودید حقیقتش من نمی دونم دقیقا چه کاری باید انجام بدم. هر کاری دستور بفرمایید به روی چشم.

**Comment by ykh** [comment]
Hi again :smile: 
If I know how to build fonts from source, so maybe I can do something about bower and npm and build-system also.
BTW Tnx @rastikerdar for these nice fonts, I wish to see more nice fonts in the future :heart:

**Comment by ykh** [comment]
Bower supported right now, and It's pretty fine to me. TNX
But I will submit another isssue about `digits` in Persian format, It seems gone in this version!
